# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
