# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='rule_123P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketID', models.CharField(max_length=264)),
                ('protocol', models.CharField(max_length=264)),
                ('srcVLAN', models.IntegerField()),
                ('srcIP', models.GenericIPAddressField()),
                ('srcPort', models.IntegerField()),
                ('dstVLAN', models.IntegerField()),
                ('dstIP', models.GenericIPAddressField()),
                ('dstPort', models.IntegerField()),
            ],
        ),
    ]
