# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_rule_123p'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rule_123p',
            table='rule_123P    ',
        ),
    ]
