# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20171107_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namefile', models.CharField(max_length=264)),
                ('contentfile', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'file_upload',
            },
        ),
        migrations.AlterField(
            model_name='rule_123p',
            name='dstPort',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='rule_123p',
            name='dstVLAN',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='rule_123p',
            name='srcPort',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='rule_123p',
            name='srcVLAN',
            field=models.CharField(max_length=264),
        ),
    ]
