# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20171111_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='namefile',
        ),
    ]
