# Generated by Django 2.1.3 on 2020-01-05 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'Input',
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='webpage',
        ),
        migrations.DeleteModel(
            name='file_upload',
        ),
        migrations.DeleteModel(
            name='image_upload',
        ),
        migrations.DeleteModel(
            name='rule_123P',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='first_app.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='first_app.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fee',
            field=models.CharField(max_length=264, unique=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
