# Generated by Django 2.1.3 on 2020-01-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_auto_20200105_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fee',
            field=models.TextField(),
        ),
    ]
