# Generated by Django 2.1.3 on 2020-01-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_auto_20200105_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
    ]
